all:
	ruby garbage_collector.rb &  
	ruby garbage_collector.rb &
	ruby garbage_collector.rb &
	ruby garbage_collector.rb &
	ruby garbage_collector.rb &
	ruby garbage_collector.rb &
	ruby garbage_collector.rb &
	ruby garbage_collector.rb &
	ruby garbage_collector.rb &
	ruby garbage_collector.rb &
